[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "edlio"
author = "Matthias Klumpp"
author-email = "matthias@tenstral.net"
home-page = "https://edl.readthedocs.io/"
